# Generated by Django 5.2 on 2025-04-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
