# Generated by Django 5.2 on 2025-04-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_current_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_token',
        ),
    ]
